version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mermer_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: websitedb
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mermer_network

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: mermer_backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: websitedb
    ports:
      - "3000:3000"
    volumes:
      - ./public:/app/public
    depends_on:
      - mysql
    networks:
      - mermer_network

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: mermer_frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:3000/api
    depends_on:
      - backend
    networks:
      - mermer_network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: mermer_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - mermer_network

volumes:
  mysql_data:

networks:
  mermer_network:
    driver: bridge
